---

# Install jdk 8
- stat: path=/tmp/jdk-8u65-linux-x64.tar.gz
  register: jdk_file

- name: get jdk8
  shell: "wget --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' -q -O /tmp/jdk-8u65-linux-x64.tar.gz http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-x64.tar.gz"
  when: not jdk_file.stat.exists

- unarchive: src=/tmp/jdk-8u65-linux-x64.tar.gz dest=/tmp/ copy=no

- file: path=/usr/lib/jvm state=directory
  sudo: yes

- shell: mv /tmp/jdk1.8.0_65 /usr/lib/jvm/java-8-oracle
  sudo: yes
