---

# Download deb if needed
- name: Download Elasticsearch deb
  shell: curl {{curl_proxy_args}} --stderr /dev/null {{ elasticsearch.download_url }}/elasticsearch-{{ elasticsearch.version }}.deb > /tmp/elasticsearch-{{ elasticsearch.version }}.deb
  sudo: yes
  when: install_elasticsearch|bool

# Uninstall previous version if applicable
- name: Uninstalling previous version if applicable
  shell: "dpkg --remove elasticsearch"
  sudo: yes
  when: install_elasticsearch|bool

- file: path={{ elasticsearch.home_dir }} state=absent
  sudo: yes
  when: install_elasticsearch|bool

# Install the deb
- name: Install Elasticsearch deb
  shell: "dpkg -i -E --force-confnew /tmp/elasticsearch-{{ elasticsearch.version }}.deb"
  sudo: yes
  when: install_elasticsearch|bool

- include: postinstall.yml

- include: deb-configure.yml
