---
# Install Elasticsearch Plugins

- name: list installed plugins
  shell: "{{ elasticsearch.home_dir }}/bin/plugin --list"
  args:
    chdir: "{{ elasticsearch.home_dir }}"
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"
  register: elasticsearch_installed_plugins_register

- set_fact: elasticsearch_installed_plugins="{{elasticsearch_installed_plugins_register.stdout.split('\n')[1:]}}"
  when: ('No plugin detected' not in elasticsearch_installed_plugins_register.stdout) and elasticsearch_installed_plugins_register.stdout.split('\n')|length > 1

# Loop though elasticsearch installed plugins and remove them
- name: Removing installed plugins if they exist
  shell: "./bin/plugin --remove {{ item |group('^\\s*-\\s*(.*)\\s*$', 1) }} chdir={{ elasticsearch.home_dir }}"
  with_items: elasticsearch_installed_plugins
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"
  when: elasticsearch_installed_plugins is defined

- name: Installing Plugins by Name
  shell: "{{ elasticsearch.home_dir }}/bin/plugin {{java_opts}} --install {{ item.name }}"
  args:
    chdir: "{{ elasticsearch.home_dir }}"
  when: item.url is not defined
  with_items: elasticsearch.plugins.list
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"
  ignore_errors: yes
  when: elasticsearch.plugins.list is defined

- name: Installing Plugins by URL
  shell: "{{ elasticsearch.home_dir }}/bin/plugin {{java_opts}} --install {{ item.name }} -url {{ item.url }}"
  args:
    chdir: "{{ elasticsearch.home_dir }}"
  when: item.url is defined and (not item.file is defined)
  with_items: elasticsearch.plugins.list
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"
  ignore_errors: yes
  when: elasticsearch.plugins.list is defined

- name: Upload local plugins
  copy: src={{item}} dest={{elasticsearch.download_dir}}/
  with_fileglob:
    - plugins/*
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"

- name: Installing local Plugins
  shell: "{{ elasticsearch.home_dir }}/bin/plugin -install {{ item.name }} -url file:///{{elasticsearch.download_dir}}/{{ item.file }}"
  args:
    chdir: "{{ elasticsearch.home_dir }}"
  when:  item.file is defined
  with_items: elasticsearch.plugins.list
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"
  ignore_errors: yes
  when: elasticsearch.plugins.list is defined

- name: Install head plugin
  include: head.yml
  when: elasticsearch.plugins.head.install|bool

- name: Install icu plugin
  include: icu.yml
  when: elasticsearch.plugins.icu.install|bool

- name: Install searchguard plugin
  include: searchguard.yml
  when: elasticsearch.plugins.searchguard.install|bool

- name: Install kopf plugin
  include: kopf.yml
  when: elasticsearch.plugins.kopf.install|bool

# Install Marvel Plugin (for Elasticsearch monitoring)
- name: Install marvel plugin
  include: marvel.yml
  when: elasticsearch.plugins.marvel.install|bool

# Fix permissions
- file: path="{{ elasticsearch.plugins.dirname }}" state=directory
        owner={{ elasticsearch.user }} group={{ elasticsearch.group }}
        recurse=yes
