---

- file: path={{ elasticsearch.home_dir}} state=absent
  sudo: yes
  when: install_elasticsearch|bool

- file: path="{{ elasticsearch.download_dir }}" state=directory
  when: install_elasticsearch|bool

- file: path="{{ elasticsearch.download_dir }}/{{ elasticsearch.package_name }}" state=absent
  sudo: yes
  when: install_elasticsearch|bool

- stat: path={{elasticsearch.prebuilt.file}} get_checksum=yes
  register: elasticsearch_file

- shell: "curl {{curl_proxy_args}} --stderr /dev/null {{elasticsearch.prebuilt.url}}.sha1.txt"
  register: elasticsearch_sha1
  when: install_elasticsearch|bool and elasticsearch_file.stat.exists

- name: download package
  shell: wget -q -O {{ elasticsearch.prebuilt.file }} {{ elasticsearch.prebuilt.url }}
  when: install_elasticsearch|bool and (not elasticsearch_file.stat.exists or (elasticsearch_file.stat.checksum != (elasticsearch_sha1.stdout|split(' '))[0]))

- name: untar package
  unarchive: src="{{ elasticsearch.prebuilt.file }}"
             dest="{{ elasticsearch.download_dir }}"
             copy=no
  sudo: yes
  when: install_elasticsearch|bool

- name: rename ES dir
  shell: "mv {{ elasticsearch.download_dir }}/{{ elasticsearch.package_name }} {{ elasticsearch.home_dir }}"
  sudo: yes
  when: install_elasticsearch|bool

- include: postinstall.yml
