---

  - file: path=/etc/modules-load.d state=directory
    become: yes

  - name: enable OverlayFS
    copy: src=overlay.conf dest=/etc/modules-load.d/overlay.conf
    become: yes
    register: overlay
    when: ansible_kernel|version_compare(3.10, '>=')

  - name: Rebooting ...
    include: reboot.yml
    when: overlay|changed

  - set_fact: docker_version=1.7.1
    when: ansible_distribution_version|version_compare(7, '<')

  - set_fact: docker_version=1.11.2
    when: ansible_distribution_version|version_compare(7, '>=')

  - name: Configure yum to use the Docker yum repo
    copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo
    become: yes

  - file: path=/etc/systemd/system/docker.service.d state=directory
    become: yes
    when: overlay|changed

  - name: Configure systemd to run the Docker Daemon with OverlayFS
    copy: src=override.conf dest=/etc/systemd/system/docker.service.d/override.conf
    become: yes
    when: overlay|changed

  - name: Install Docker selinux package
    yum: name={{item}} state=present update_cache=yes
    with_items:
      - "docker-engine-selinux-{{docker_version}}"
    become: yes
    when: ansible_distribution_version|version_compare(7, '>=')

  - name: Install Docker package
    yum: name={{item}} state=present update_cache=yes
    with_items:
      - "docker-engine-{{docker_version}}"
    become: yes

  - name: make sure docker-python RPM is not installed
    yum:
      name: docker-python
      state: absent

  - name: Install easy_install package
    yum: name={{item}} state=latest
    become: yes
    with_items:
      - python-setuptools

  - include: pip.yml

  - name: Stop and Disbale firewalld #https://docs.docker.com/v1.6/installation/centos/#firewalld
    service: name=firewalld enabled=no state=stopped
    become: yes
    when: ansible_distribution_version|version_compare(7, '>=')

  - name: Enable Docker service on boot and Start it
    service: name=docker enabled=yes state=restarted
    become: yes
