---

  - name: Check if docker-engine-1.7.1 is installed
    command: rpm -q docker-engine-1.7.1
    ignore_errors: yes
    sudo: yes
    register: rpm_check

  - name: Install dependencies
    yum:
      name: "{{item}}"
      state: latest
      update_cache: yes
    with_items:
      - wget
    sudo: yes
    when: (rpm_check.stdout.find('is not installed') != -1)

  - name: Download the Docker rpm for centos 6.5 or above
    command: wget -O /tmp/docker-engine-1.7.1-1.el6.x86_64.rpm --no-check-certificate https://get.docker.com/rpm/1.7.1/centos-6/RPMS/x86_64/docker-engine-1.7.1-1.el6.x86_64.rpm
    register: docker_centos6
    when: (rpm_check.stdout.find('is not installed') != -1) and (ansible_distribution_version|version_compare(7, '<'))

  - name: Download the Docker rpm for centos 7 or above
    command: wget -O /tmp/docker-engine-1.7.1-1.el7.centos.x86_64.rpm --no-check-certificate https://get.docker.com/rpm/1.7.1/centos-7/RPMS/x86_64/docker-engine-1.7.1-1.el7.centos.x86_64.rpm
    register: docker_centos7
    when: (rpm_check.stdout.find('is not installed') != -1) and (ansible_distribution_version|version_compare(7, '>'))

  - name: Install Docker package
    yum: name=/tmp/docker-engine-1.7.1-1.el6.x86_64.rpm disable_gpg_check=yes update_cache=yes state=present
    sudo: yes
    when: (rpm_check.stdout.find('is not installed') != -1) and (docker_centos6|changed or docker_centos7|changed)

  - name: Install easy_install package
    yum: name={{item}} state=latest
    sudo: yes
    with_items:
      - python-setuptools

  - include: pip.yml
