---

  - name: install docker on RedHat
    yum: name={{item}} state=latest
    with_items:
      - docker

  - name: make sure docker-python RPM is not installed
    yum:
      name: docker-python
      state: absent

  - name: Install easy_install package
    yum: name={{item}} state=latest
    sudo: yes
    with_items:
      - python-setuptools

  - include: pip.yml

  - name: Enable Docker service on boot
    service: name=docker enabled=yes

  - name: Start the Docker daemon
    service: name=docker state=started
