---

# Check whether we have aleady installed the same version
- set_fact: previous_kafka_version="{% if ansible_local is defined and ansible_local['kafka'] is defined %}{{ansible_local['kafka']['kafka']['version']}}{% else %}''{% endif %}"

- debug: msg="the previous version of kafka was '{{ previous_kafka_version }}'"

- debug: msg="the expected version of kafka is '{{ kafka.version }}'"

- set_fact: install_kafka="{{previous_kafka_version != kafka.version}}"

# Install Kafka
- include: install.yml
  when: install_kafka

# Configure kafka
- include: configure.yml

- file: path=/etc/ansible/facts.d state=directory
  sudo: yes

- template: src=kafka.fact dest="/etc/ansible/facts.d/kafka.fact"
  sudo: yes
