---

kafka:
  user: "{{kafka_user | default('kafka')}}"
  partitions: "{{kafka_partitions | default('1')}}"
  version: "{{ kafka_version | default('0.9.0.1') }}"
  package_name: "{{ kafka_package_name | default('kafka_'+(scala_version | default('2.11'))|string+'-'+(kafka_version | default('0.9.0.1'))|string) }}"
  download_dir: "{{ kafka_download_dir | default('/tmp') }}"
  file: "{{kafka_download_dir | default('/tmp')}}/{{kafka_download_file | default(kafka_package_name | default('kafka_'+(scala_version | default('2.11'))|string+'-'+(kafka_version | default('0.9.0.1'))|string)+'.tgz') }}"
  url: "{{kafka_download_package_url | default(apache_mirror+'kafka/'+(kafka_version | default('0.9.0.1'))|string+'/'+(kafka_download_file | default(kafka_package_name | default('kafka_'+(scala_version | default('2.11'))|string+'-'+(kafka_version | default('0.9.0.1'))|string)+'.tgz'))) }}"
  home_dir: "{{ kafka_home_dir | default('/usr/local/kafka') }}"
  log_dir: "{{ kafka_log_dir | default('/var/log/kafka') }}"

  service:
    enabled: "{{ kafka_service_enabled | default('no') }}"
    state: "{{ kafka_service_state | default('stopped') }}"

  config:
    port: "{{kafka_config_port | default('9092')}}"
    hostname: "{{kafka_config_hostname | default('localhost')}}"
    broker:
      id: "{{kafka_config_broker_id | default('0')}}"
    advertised:
      hostname: "{{kafka_config_advertised_hostname | default(kafka_config_hostname | default('localhost'))}}"
      port: "{{kafka_config_advertised_port | default(kafka_config_port | default('9092'))}}"

  log:
    dirs: "{{ kafka_log_dirs | default('/var/lib/kafka') }}"
