---

- name: Retrieve zeppelin app
  uri: url="{{marathon.api}}/{{zeppelin.id}}" HEADER_Content-Type="application/json" method=GET return_content=yes status_code=200,404
  register: zeppelin_app_response

- name: remove zeppelin app
  uri: url={{marathon.api}}/{{zeppelin.id}} HEADER_Content-Type="application/json" method=DELETE return_content=yes status_code=200,204
  when: "'message' not in {{zeppelin_app_response.content}}"

- name: copy zeppelin marathon json file
  template: src=zeppelin.json dest=/tmp/zeppelin.json

- name: Install zeppelin application
  shell: 'curl -X POST -H "Content-Type: application/json" {{marathon.api}}?force=true -d@/tmp/zeppelin.json'
  register: install_zeppelin_response

- debug: var=install_zeppelin_response
  when: install_zeppelin_response is defined

- name: Wait untils zeppelin app is available
  shell: curl --head --silent {{marathon.api}}/{{zeppelin.id}}/tasks
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 12
  delay: 5
