---

# Install Debian dependencies
- name: Install Debian dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - tar
    - curl
    - wget
  sudo: yes
  when: ansible_os_family == 'Debian'

# Install Redhat dependencies
- name: Install Redhat dependencies
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - tar
    - curl
    - wget
  sudo: yes
  when: ansible_os_family == 'RedHat'

- file: path="{{ zookeeper.home_dir }}" state=absent
  sudo: yes

- file: path="{{ zookeeper.download_dir }}" state=directory

- stat: path={{zookeeper.file}} get_checksum=yes
  register: zookeeper_file

- shell: curl {{curl_proxy_args}} --stderr /dev/null {{zookeeper.sha1}}
  register: zookeeper_sha1
  when: zookeeper_file.stat.exists

- name: get zookeeper
  shell: "wget -q -O {{zookeeper.file}} {{zookeeper.url}}"
  when: not zookeeper_file.stat.exists or (zookeeper_file.stat.checksum != (zookeeper_sha1.stdout|split(' '))[0])

- name: Extract and install Zk
  unarchive: src="{{ zookeeper.file }}"
             dest={{ zookeeper.download_dir }}
             copy=no

- name: rename install dir
  shell: "mv {{ zookeeper.download_dir}}/{{zookeeper.package_name}} {{zookeeper.home_dir}}"
  sudo: yes

- name: Configure Zk
  template: src=zoo.cfg
            dest={{ zookeeper.home_dir }}/conf/
  sudo: yes

- name: Create zookeeper log dir if it does not exist
  file: path={{ zookeeper.log.dir }}
        state=directory
  sudo: yes

- name: Create zookeeper data dir if it does not exist
  file: path={{ zookeeper.config.dataDir }}
        state=directory
  sudo: yes

