---

- name: install zookeeper
  include: install.yml
  when: not (zk_configure|default('no'))|bool

- name: configure and launch zookeeper
  include: configure.yml
  when: (zk_configure|default('no'))|bool
