---

  - name: add squid
    include: squid.yml
    when: proxy_enabled|bool and proxy_mock|bool

  - name: add proxy Settings for apt-get
    include: apt.yml
    when: ansible_os_family == "Debian"

  - name: add proxy Settings for yum
    include: yum.yml
    when: ansible_os_family == "RedHat"

  - name: add proxy Settings for wget
    include: wget.yml
    when: proxy_enabled|bool
