---

  - include: proxy_facts.yml
    when: not proxy_host is defined

  - name: add squid
    include: squid.yml
    when: proxy_enabled|bool and proxy_mock|bool

  - name: add proxy Settings for apt-get
    include: apt.yml
    when: ansible_os_family == "Debian"

  - name: add proxy Settings for yum
    include: yum.yml
    when: ansible_os_family == "RedHat"

  - name: add proxy Settings for wget
    include: wget.yml
    when: proxy_enabled|bool

  - name: add proxy Settings for curl
    include: curl.yml

  - name: add proxy Settings for pip
    include: pip.yml

  - set_fact: proxy_env={}
    when: not proxy_enabled|bool

  - set_fact:
      proxy_env:
        http_proxy: "{{proxy_url}}"
        https_proxy: "{{proxy_url}}"
        no_proxy: "{{no_proxy}}"
    when: proxy_enabled|bool
