---

  # We must install pip before we can use the pip module below
  - easy_install: name=pip #state=latest required ansible 2.x
    sudo: yes

  - name: Upgrade latest passlib
    pip:
      name: passlib
      state: latest
    sudo: yes

  - lineinfile: dest=/etc/apt/apt.conf regexp='^.*Proxy' state=absent
    sudo: yes
    when: ansible_os_family == "Debian"

  - apt: name={{item}} state=latest update_cache=yes cache_valid_time=3600
    sudo: yes
    with_items:
      - squid
      - apache2-utils
    when: ansible_os_family == "Debian"

  - lineinfile: dest=/etc/yum.conf regexp='^proxy.*=' state=absent
    sudo: yes
    when: ansible_os_family == "RedHat"

  - yum: name={{item}} state=latest update_cache=yes
    sudo: yes
    with_items:
      - squid
      - httpd-tools
    when: ansible_os_family == "RedHat"

  - file: path=/etc/squid3 src=/etc/squid state=link
    sudo: yes
    when: ansible_os_family == "RedHat"

  - file: path=/etc/squid3/users mode=644 state=touch
    sudo: yes

  - name: add {{proxy_login}} to authorized users
    sudo: yes
    htpasswd:
      create: yes
      path: /etc/squid3/users
      name: "{{proxy_login}}"
      password: "{{proxy_password}}"
      state: present

  - set_fact: ncsa_auth=/usr/lib/squid3/basic_ncsa_auth
    when: ansible_os_family == "Debian"

  - set_fact: ncsa_auth=/usr/lib64/squid/ncsa_auth
    when: ansible_os_family == "RedHat"

  - set_fact: cache_dir=/var/spool/squid3
    when: ansible_os_family == "Debian"

  - set_fact: cache_dir=/var/spool/squid
    when: ansible_os_family == "RedHat"

  - template: src=squid.conf dest=/etc/squid3/ mode=644
    register: squid_conf
    sudo: yes

  - set_fact: squid_service=squid3
    when: ansible_os_family == "Debian"

  - set_fact: squid_service=squid
    when: ansible_os_family == "RedHat"

  - service: name={{squid_service}} state=restarted
    sudo: yes
    when: squid_conf|changed
