---

- file: path={{spark.base_dir}} state=absent

- name: retreive spark from git
  git: repo={{ spark.build.git.url }}
       version={{ spark.build.git.branch }}
       dest={{ spark.base_dir }}
       update=yes
       depth=1
  sudo: yes

