---

# Install jdk 6
- stat: path=/tmp/jdk-6u45-linux-x64.bin
  register: jdk_file

- name: get jdk6
  shell: "wget --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' -q -O /tmp/jdk-6u45-linux-x64.bin http://download.oracle.com/otn-pub/java/jdk/6u45-b06/jdk-6u45-linux-x64.bin"
  when: not jdk_file.stat.exists

- file: path=/tmp/jdk-6u45-linux-x64.bin mode=a+x state=file

- shell: /tmp/jdk-6u45-linux-x64.bin chdir=/tmp
  sudo: yes

- file: path=/usr/lib/jvm state=directory
  sudo: yes

- shell: mv /tmp/jdk1.6.0_45 /usr/lib/jvm/java-6-oracle
  sudo: yes
