---

- name: Fetch Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_version

- include: prebuild-jdk.yml
  when: (java_version.stdout|length < 1 or (java_version.stdout | version_compare('1.{{java_major_version}}', '<'))) #and prebuild|bool

#- include: jdk.yml
#  when: not prebuild|bool and (java_version.stdout|length < 1 or (java_version.stdout | version_compare('1.{{java_major_version}}', '<')))
