---

  - template: src=apt.conf dest=/etc/apt/apt.conf mode=644
    sudo: yes
    when: proxy_enabled|bool

  - lineinfile: dest=/etc/apt/apt.conf regexp='^.*Proxy' state=absent
    sudo: yes
    when: not proxy_enabled|bool
