---

- name: gather facts from proxy server
  setup:
  delegate_to: "{{groups.proxy | first}}"
  register: registry_facts

- set_fact:
    proxy_host: "{{registry_facts.ansible_facts.ansible_default_ipv4['address']}}"
    proxy_url: "http://{{ {% if (proxy_login is defined) and (proxy_password is defined) %}(proxy_login|string) + ':' + (proxy_password|string) + '@' {% endif %}}}{{registry_facts.ansible_facts.ansible_default_ipv4['address']}}:{{proxy_port}}"
    proxy_server: "http://{{registry_facts.ansible_facts.ansible_default_ipv4['address']}}:{{proxy_port}}"
