---

- name: apache preferred mirror
  shell: curl {{curl_proxy_args}} --stderr /dev/null https://www.apache.org/dyn/closer.cgi?as_json=1
  register: apache_mirrors
  ignore_errors: yes

- set_fact: apache_mirror="{{(apache_mirrors.stdout|from_json).preferred}}"
  when: apache_mirrors|success

- set_fact: apache_mirror="{{default_apache_mirror}}"
  when: not apache_mirrors|success
