---

- file: path="{{ spark.download_dir }}" state=directory

- stat: path={{spark.prebuilt.file}}
  register: spark_file

- name: get spark prebuilt asc
  shell: wget -q -O {{spark.prebuilt.file}}.asc {{spark.prebuilt.url}}.asc
  when: spark_file.stat.exists

- name: get spark keys
  shell: wget -q -O {{ spark.install_dir }}/KEYS {{apache_mirror}}spark/KEYS
  register: spark_keys
  when: spark_file.stat.exists

- name: import spark keys
  shell: gpg --import {{ spark.install_dir }}/KEYS
  when: spark_file.stat.exists and spark_keys|success

- name: verify spark prebuilt file
  shell: gpg --verify {{spark.prebuilt.file}}.asc {{spark.prebuilt.file}}
  register: spark_file_check
  when: spark_file.stat.exists

# Download pre-built
- name: download spark prebuilt package
  shell: "wget -q -O {{spark.prebuilt.file}} {{spark.prebuilt.url}}"
  when: not spark_file.stat.exists or (not spark_file_check|success)

- name: untar package
  unarchive: src="{{spark.prebuilt.file}}"
             dest="{{spark.install_dir}}"
             copy=no

- file: path={{spark.base_dir}} state=absent
  sudo: yes

- name: rename spark base dir
  shell: "mv {{ spark.install_dir }}/{{ spark.prebuilt.package_name }} {{ spark.base_dir }}"
  sudo: yes
