---

- name: ensure spark dirs exist
  file: state=directory path={{ item }} owner={{ spark.user }} group={{ spark.group }} recurse=yes
  with_items:
    - "{{ spark.base_dir }}"
    - "{{ spark.log_dir }}"
    - "{{ spark.run_dir }}"
  sudo: yes

- name: Create symlink for config dir
  file: src="{{ spark.conf_dir }}"
        dest="{{ spark.config.dirname }}"
        state=link
        force=yes
  sudo: yes

- name: copy configuration files
  template: src={{ item }}.j2 dest={{spark.config.dirname}}/{{item}} owner={{spark.user}}
  with_items:
     - spark-defaults.conf
     - spark-env.sh
  sudo: yes

- name:  install spark binaries
  template: src=spark-shim.j2
            dest="{{ spark.bin_dir }}/{{ item }}.sh"
            mode=0755
  with_items:
    - spark-class
    - spark-shell
    - spark-sql
    - spark-submit
  sudo: yes
