---

- name: ensure base dir exists
  file: path="{{ spark.install_dir }}" state=directory owner="{{ ansible_ssh_user }}" group="{{ ansible_ssh_user }}"

- name: ensure spark group exist
  group: name={{spark.group}}
  sudo: yes

- name: ensure spark user exist
  user: name={{spark.user}} group={{spark.group}}
  sudo: yes
