---

- name: Add sbt apt reporitory
  apt_repository: repo="deb https://dl.bintray.com/sbt/debian /"
  when: ansible_os_family == 'Debian'

- name: Add sbt apt key
  apt_key: keyserver="keyserver.ubuntu.com" id="642AC823"
  when: ansible_os_family == 'Debian'

- name: Install sbt package for Debian
  apt: name=sbt state=present force=yes
       update_cache=yes cache_valid_time=3600
  when: ansible_os_family == 'Debian'

# required ansible 2.1
#- name: add sbt yum repository
#  yumrepo: name=sbt base_url=https://bintray.com/sbt/rpm/rpm
#  when: ansible_os_family == 'RedHat'

- name: add sbt yum repository
  shell: "curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo"
  sudo: yes
  when: ansible_os_family == 'RedHat'

- name: Install sbt package for RedHat
  yum: name='sbt' state=present update_cache=yes enablerepo=bintray--sbt-rpm
  sudo: yes
  when: ansible_os_family == 'RedHat'

# Manual installation
# - name: Download sbt jar
#   get_url: url={{ sbt.jar }} dest={{ sbt.install_dir }}

# - name: Install sbt bin
#   file: src="{{ sbt.install_dir }}/sbt-launch.jar" path='/usr/bin/sbt-launch' state=link mode=0755
