# docker-registry Ansible Meta
galaxy_info:
  author: "Stéphane Manciot"
  company: EBIZNEXT
  license: MIT
  min_ansible_version: 2.0
dependencies:
  - {role: docker}
  - {role: docker.registry, when: "'registry' in group_names"}
  - {role: docker.registry.client}
