---
# Install Elasticsearch Plugins

# Loop though elasticsearch_plugins and install them
- name: Removing Plugins if they exist
  shell: "{{ elasticsearch.home_dir }}/bin/plugin --remove {{ item.name }}"
  args:
    chdir: "{{ elasticsearch.home_dir }}"
  with_items: elasticsearch.plugins.list
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"
  ignore_errors: yes

- name: Installing Plugins by Name
  shell: "{{ elasticsearch.home_dir }}/bin/plugin {{java_opts}} --install {{ item.name }}"
  args:
    chdir: "{{ elasticsearch.home_dir }}"
  when: item.url is not defined
  with_items: elasticsearch.plugins.list
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"
  ignore_errors: yes

- name: Installing Plugins by URL
  shell: "{{ elasticsearch.home_dir }}/bin/plugin {{java_opts}} --install {{ item.name }} -url {{ item.url }}"
  args:
    chdir: "{{ elasticsearch.home_dir }}"
  when: item.url is defined and (not item.file is defined)
  with_items: elasticsearch.plugins.list
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"
  ignore_errors: yes

- name: Upload local plugins
  copy: src={{item}} dest={{elasticsearch.download_dir}}/
  with_fileglob:
    - plugins/*
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"

- name: Installing local Plugins
  shell: "{{ elasticsearch.home_dir }}/bin/plugin -install {{ item.name }} -url file:///{{elasticsearch.download_dir}}/{{ item.file }}"
  args:
    chdir: "{{ elasticsearch.home_dir }}"
  when:  item.file is defined
  with_items: elasticsearch.plugins.list
  sudo: yes
  sudo_user: "{{ elasticsearch.user }}"
  ignore_errors: yes

- name: Install head plugin
  include: head.yml
  when: elasticsearch.plugins.head.install|bool

- name: Install icu plugin
  include: icu.yml
  when: elasticsearch.plugins.icu.install|bool

- name: Install searchguard plugin
  include: searchguard.yml
  when: elasticsearch.plugins.searchguard.install|bool

# Install Marvel Plugin (for Elasticsearch monitoring)
- name: Install marvel plugin
  include: marvel.yml
  when: elasticsearch.plugins.marvel.install|bool

# Fix permissions
- file: path="{{ elasticsearch.plugins.dirname }}" state=directory
        owner={{ elasticsearch.user }} group={{ elasticsearch.group }}
        recurse=yes
