---

# Check whether we have aleady installed the same version
- set_fact: previous_flume_version="{% if ansible_local is defined and ansible_local['flume'] is defined %}{{ansible_local['flume']['flume']['version']}}{% else %}''{% endif %}"

- debug: msg="the previous version of flume was '{{ previous_flume_version }}'"

- debug: msg="the expected version of flume is '{{ flume.version }}'"

- set_fact: install_flume="{{previous_flume_version != flume.version}}"

# Install flume
- include: install.yml

# Configure flume
- include: configure.yml

- file: path=/etc/ansible/facts.d state=directory
  sudo: yes

- template: src=flume.fact dest="/etc/ansible/facts.d/flume.fact"
  sudo: yes
