---

- name: clean previous dependencies
  shell: "rm -f {{flume.ext.dir}}/*.jar"
  sudo: yes

#elasticsearch dependencies
- file: path="{{ elasticsearch.download_dir }}" state=directory

- stat: path={{elasticsearch.file}} get_checksum=yes
  register: elasticsearch_file

- shell: curl {{curl_proxy_args}} --stderr /dev/null {{ elasticsearch.url }}.sha1.txt
  register: elasticsearch_sha1
  when: elasticsearch_file.stat.exists

- name: download elasticsearch package
  shell: wget -q -O {{elasticsearch.file}} {{ elasticsearch.url }}
  when: not elasticsearch_file.stat.exists or (elasticsearch_file.stat.checksum != (elasticsearch_sha1.stdout|split(' '))[0])

- name: untar elasticsearch package
  unarchive: src="{{elasticsearch.file}}"
             dest="{{ elasticsearch.download_dir }}"
             copy=no
  sudo: yes

- name: copy elasticsearch dependencies
  shell: "cp *.jar {{flume.ext.dir}}/ chdir={{elasticsearch.download_dir}}/{{ elasticsearch.package_name }}/lib"
  sudo: yes

#maven dependencies
- include: lxml.yml

#zookeeper dependencies
- name: download zookeeper package
  maven_artifact:
    group_id: org.apache.zookeeper
    artifact_id: zookeeper
    version: "{{zookeeper_version}}"
    extension: jar
    dest: "{{flume.ext.dir}}/zookeeper-{{zookeeper_version}}.jar"
  environment: "{{proxy_env}}"
#  shell: wget -q -O {{flume.ext.dir}}/zookeeper-{{zookeeper_version}}.jar https://repo1.maven.org/maven2/org/apache/zookeeper/zookeeper/{{zookeeper_version}}/zookeeper-{{zookeeper_version}}.jar
  sudo: yes
