---

- name: Build Zeppelin
  shell: "mvn clean package {{ zeppelin.build.opts }}"
  args:
    chdir: "{{ zeppelin.base_dir }}"
  sudo: yes

- local_action: file path={{ zeppelin.local_dir }} state=directory
  sudo: no

- name: fetch zeppelin package
  fetch:
    src: "{{ zeppelin.build.distrib.file }}"
    dest: "{{ zeppelin.local_dir }}/"
    flat: yes
