---

- name: retrieve zeppelin from tarball
  include: install_from_tarball.yml
  when: zeppelin.build.checkout == 'tarball'

- name: retrieve zeppelin from git
  include: install_from_git.yml
  when: zeppelin.build.checkout == 'git'
