---

- name: Fix permissions
  file: path={{ zeppelin.base_dir }} owner={{ zeppelin.user }} group={{ zeppelin.group }} state=directory recurse=yes

- name: Copy zeppelin-site.xml file
  template: src=zeppelin-site.xml.j2 dest="{{ zeppelin.base_dir }}/conf/zeppelin-site.xml"

- name: gather facts from zookeeper servers
  setup:
    filter: ansible_local
  delegate_to: "{{item}}"
  with_items: "{{groups['zookeeper']|list}}"
  register: zookeeper_facts
  when: groups.zookeeper is defined and (not mesos_zookeepers is defined)

- set_fact: mesos_zookeepers="zk://{{ zookeeper_facts.results | map(attribute='ansible_facts.ansible_local.datalab.zookeeper.addr') | list | join(',') }}/mesos"
  when: zookeeper_facts.results is defined

- name: Copy zeppelin-env.sh file
  template: src=zeppelin-env.sh.j2 dest="{{ zeppelin.base_dir }}/conf/zeppelin-env.sh"

- name: Make sure zeppelin-daemon.sh is executable
  file: path="{{ zeppelin.base_dir }}/bin/zeppelin-daemon.sh" owner={{ zeppelin.user }} group={{ zeppelin.group }} mode=0744

# NOTE: This is a hack to make sure that zeppelin is stopped by default (it should be already)
# as it is not installed as a service (zeppelin.service_action flag is set to stop).
- name: Handle service status
  shell: "{{ zeppelin.base_dir }}/bin/zeppelin-daemon.sh {{ zeppelin.service.action }}"
#  sudo: yes
#  sudo_user: "{{zeppelin.user}}"
#  when: zeppelin.service.action == "start"
