---

- name: ensure base dir exists
  file: path="{{ zeppelin.install_dir }}" state=directory owner="{{ ansible_ssh_user }}" group="{{ ansible_ssh_user }}"

- name: ensure zeppelin group exist
  group: name={{zeppelin.group}}
  sudo: yes

- name: ensure zeppelin user exist
  user: name={{zeppelin.user}} group={{zeppelin.group}}
  sudo: yes

- name: install from pre-built packaged
  include: install_from_prebuilt.yml
  when: not zeppelin.build.do|bool and not zeppelin_local_file.stat.exists

- name: install from source
  include: install_from_source.yml
  when: zeppelin.build.do|bool and not zeppelin_local_file.stat.exists

- name: install from local
  include: install_from_local.yml
  when: zeppelin_local_file.stat.exists
