---

- file: path={{zeppelin.base_dir}} state=absent
  sudo: yes

- name: retreive zeppelin from git
  git: repo={{ zeppelin.build.git.url }}
       version={{zeppelin.build.git.branch}}
       dest={{ zeppelin.base_dir }}
       update=yes
       depth=1
  sudo: yes
